USE eMergeBIS4530DB
GO
truncate TABLE [eMergeBIS4530DB].[SAPIENS].[LG]
GO
truncate TABLE [eMergeBIS4530DB].[SAPIENS].[LGLEX]
GO
truncate TABLE [eMergeBIS4530DB].[SAPIENS].[LGDLK]
GO
truncate TABLE [eMergeBIS4530DB].[SAPIENS].[LGCAT]
GO
truncate TABLE [eMergeBIS4530DB].[SAPIENS].[LGCAT]
GO
truncate TABLE [eMergeBIS4530DB].[SAPIENS].[LGDAT]
GO
truncate TABLE [eMergeBIS4530DB].[SAPIENS].[LGSEC]
GO
truncate TABLE [eMergeBIS4530DB].[SAPIENS].[LGCMN]
GO
truncate TABLE [eMergeBIS4530DB].[SAPIENS].[LGCCM1]
GO
truncate TABLE [eMergeBIS4530DB].[SAPIENS].[LGSWS]
GO


quit